deploymentName: cart-service-deployment
serviceName: cart-service
appLabel: cart-service
appName: cart-service

replicaCount: 1

image:
  repository: miloszk/cart-service
  tag: v7.1

containerPort: 8083

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

appname_enabled: true
profile_enabled: true
keycloak_enabled: true
config_enabled: true
eureka_enabled: true
otel_enabled: true
configserver_secrets_enabled: false

userdb_enabled: false
productdb_enabled: false
cartdb_enabled: true
orderdb_enabled: false