{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-pvc
  labels:
    app: keycloak-postgres
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size }}
  {{- if .Values.postgresql.primary.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.primary.persistence.storageClass }}
  {{- end }}
{{- end }}